version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    networks:
      - whisper-net

  db:
    image: mysql:8.0
    container_name: whisper-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: whisper
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - whisper-net

volumes:
  db_data:

networks:
  whisper-net:
